apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anubiswatch.fullname" . }}-config
  labels:
    {{- include "anubiswatch.labels" . | nindent 4 }}
data:
  anubis.yaml: |
    server:
      host: 0.0.0.0
      port: {{ .Values.config.server.port }}
      grpc_port: {{ .Values.service.grpcPort }}
      tls:
        enabled: {{ .Values.config.server.tls.enabled }}
      allowed_origins: {{ .Values.config.server.allowedOrigins | toJson }}

    auth:
      type: {{ .Values.config.auth.type }}
      local:
        admin_email: {{ .Values.config.auth.local.adminEmail | quote }}

    dashboard:
      enabled: {{ .Values.config.dashboard.enabled }}

    storage:
      path: {{ .Values.config.storage.path }}
      encryption:
        enabled: {{ .Values.config.storage.encryption.enabled }}

    necropolis:
      enabled: {{ .Values.config.necropolis.enabled }}

    logging:
      level: {{ .Values.config.logging.level }}
      format: {{ .Values.config.logging.format }}
      output: stdout
