apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anubiswatch.fullname" . }}-config
  labels:
    {{- include "anubiswatch.labels" . | nindent 4 }}
data:
  anubis.yaml: |
    server:
      host: 0.0.0.0
      port: {{ .Values.config.server.port }}
      grpc_port: {{ .Values.service.grpcPort }}
      tls:
        enabled: {{ .Values.config.server.tls.enabled }}
        {{- if .Values.config.server.tls.cert }}
        cert: {{ .Values.config.server.tls.cert | quote }}
        {{- end }}
        {{- if .Values.config.server.tls.key }}
        key: {{ .Values.config.server.tls.key | quote }}
        {{- end }}
        min_version: {{ .Values.config.server.tls.min_version }}
        prefer_server: {{ .Values.config.server.tls.prefer_server }}
      trusted_proxies: {{ .Values.config.server.trustedProxies | toJson }}
      allowed_origins: {{ .Values.config.server.allowedOrigins | toJson }}

    auth:
      enabled: true
      type: {{ .Values.config.auth.type }}
      local:
        admin_email: {{ .Values.config.auth.local.adminEmail | quote }}

    dashboard:
      enabled: {{ .Values.config.dashboard.enabled }}

    storage:
      path: {{ .Values.config.storage.path }}
      encryption:
        enabled: {{ .Values.config.storage.encryption.enabled }}

    necropolis:
      enabled: {{ .Values.config.necropolis.enabled }}

    logging:
      level: {{ .Values.config.logging.level }}
      format: {{ .Values.config.logging.format }}
      output: stdout
