apiVersion: v1
kind: Service
metadata:
  name: {{ include "anubiswatch.fullname" . }}
  labels:
    {{- include "anubiswatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if gt (int .Values.service.grpcPort) 0 }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "anubiswatch.selectorLabels" . | nindent 4 }}

{{ if .Values.config.necropolis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "anubiswatch.fullname" . }}-headless
  labels:
    {{- include "anubiswatch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if gt (int .Values.service.grpcPort) 0 }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    - port: {{ .Values.service.clusterPort }}
      targetPort: raft
      protocol: TCP
      name: raft
  selector:
    {{- include "anubiswatch.selectorLabels" . | nindent 4 }}
{{ end }}
