server:
  host: "0.0.0.0"
  port: 9393
  tls:
    enabled: false

storage:
  path: "./data"

auth:
  enabled: true
  type: local
  local:
    admin_email: "admin@anubis.watch"
    admin_password: "SecurePass123!"

dashboard:
  enabled: true
  branding:
    title: "AnubisWatch"
    theme: "auto"

logging:
  level: "info"
  format: "text"
  output: "stdout"
