import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, expect, test, vi } from 'vitest'
import { Alerts } from './Alerts'
const mocks=vi.hoisted(() => ({ channel:vi.fn(), rule:vi.fn(), channels:[{ id:'one',name:'Existing',type:'webhook',enabled:true,config:{} }] }))
vi.mock('../api/hooks', () => ({ useChannels: () => ({ channels:mocks.channels,loading:false,createChannel:mocks.channel,refetch:vi.fn() }),useRules: () => ({ rules:[],loading:false,createRule:mocks.rule,refetch:vi.fn() }),useIncidents: () => ({ incidents:[],loading:false,refetch:vi.fn() }) }))
function deferred() { let resolve!: () => void; let reject!: (e: Error) => void; const promise=new Promise<void>((a,b) => { resolve=a;reject=b }); return { promise,resolve,reject } }
type Kind='channel'|'rule'
function input(kind:Kind) { return screen.getByPlaceholderText(kind === 'channel' ? 'e.g., Ops Slack' : 'e.g., High Latency') }
function open(kind:Kind,name='First draft') { fireEvent.click(screen.getByRole('tab', { name:kind === 'channel' ? /channels/i : /rules/i })); fireEvent.click(screen.getByRole('button', { name:kind === 'channel' ? 'Add Channel' : 'Add Rule' })); fireEvent.change(input(kind), { target:{value:name} }); if (kind === 'channel') fireEvent.change(screen.getByPlaceholderText('https://example.com/webhook'), { target:{value:'https://fixture.invalid'} }) }
function submit(kind:Kind) { fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name:kind === 'channel' ? 'Add Channel' : 'Add Rule' })) }
function setup() { mocks.channel.mockReset();mocks.rule.mockReset();return render(<Alerts />) }
afterEach(cleanup)
for (const kind of ['channel','rule'] as const) {
 test(kind+' current success and failure',async () => { setup();mocks[kind].mockResolvedValue(undefined);open(kind);submit(kind);await act(async () => {});expect(screen.queryByRole('dialog')).toBeNull();cleanup();setup();mocks[kind].mockRejectedValue(new Error('current failure'));open(kind);submit(kind);await act(async () => {});expect(screen.getByText('current failure')).toBeInTheDocument();expect(within(screen.getByRole('dialog')).getByRole('button',{name:kind === 'channel' ? 'Add Channel' : 'Add Rule'})).toBeEnabled() })
 test(kind+' stale success preserves new pending save',async () => { const old=deferred(),current=deferred();setup();mocks[kind].mockReturnValueOnce(old.promise).mockReturnValueOnce(current.promise);open(kind);submit(kind);fireEvent.click(screen.getByRole('button',{name:'Cancel'}));open(kind,'New draft');submit(kind);await act(async () => {old.resolve();await old.promise});expect(input(kind)).toHaveValue('New draft');expect(screen.getByRole('button',{name:'Saving...'})).toBeDisabled();await act(async () => {current.resolve();await current.promise});expect(screen.queryByRole('dialog')).toBeNull() })
 test(kind+' stale failure cannot set error or unlock current save',async () => { const old=deferred(),current=deferred();setup();mocks[kind].mockReturnValueOnce(old.promise).mockReturnValueOnce(current.promise);open(kind);submit(kind);fireEvent.click(screen.getByRole('button',{name:'Cancel'}));open(kind,'New draft');submit(kind);await act(async () => {old.reject(new Error('old failure'));await old.promise.catch(() => {})});expect(screen.queryByText('old failure')).toBeNull();expect(screen.getByRole('button',{name:'Saving...'})).toBeDisabled();await act(async () => {current.resolve();await current.promise}) })
 test(kind+' stale failure cannot leak into another kind of form',async () => { const old=deferred();setup();mocks[kind].mockReturnValue(old.promise);open(kind);submit(kind);fireEvent.click(screen.getByRole('button',{name:'Cancel'}));const other=kind === 'channel' ? 'rule' : 'channel';open(other,'Other draft');await act(async () => {old.reject(new Error('old failure'));await old.promise.catch(() => {})});expect(input(other)).toHaveValue('Other draft');fireEvent.click(screen.getByRole('button',{name:'Cancel'}));open(kind);expect(screen.queryByText('old failure')).toBeNull() })
}
